baseURL = "https://goodideal.github.io/codevai/"
languageCode = "zh-cn"
title = "CodeVai"
theme = "hugo-theme-stack"
defaultContentLanguage = "zh"
hasCJKLanguage = true
enableRobotsTXT = true

[pagination]
pagerSize = 10

[permalinks]
post = "/post/:slug/"
page = "/:slug/"

[outputs]
home = ["HTML", "RSS", "JSON"]
section = ["HTML", "RSS"]

[imaging]
resampleFilter = "lanczos"
quality = 85